import { StyleSheet } from 'react-native';
     const ListeStyle = StyleSheet.create({
        imageListe:{
            width: "100%",
        },
        w_100:{
            width: "100%",
        },
        txt_categ:{
            fontSize:20,
            color:"white",
            alignSelf:"center",
            fontFamily:"futuraMd"
        },
        titre_event:{
            fontSize:25,
            textAlign:"center",
            color:"#E80EAE",
            fontFamily:"futuraMd"
        },
        date_debut_fin:{
            fontSize:20,
            textAlign:"center",
            fontWeight:"700",
            fontFamily:"futuraMd"
        },
        adresse_txt:{
            fontSize:20,
            textAlign:"center",
            fontWeight:"600",
            fontFamily:"futuraMd"
        },
        ville_txt:{
            fontSize:20,
            textAlign:"center",
            fontWeight:"600",
            fontFamily:"futuraMd"
        },
        btn_details:{
            width:50,
            height:52,
            alignSelf:"center",
            fontFamily:"futuraMd"
        },
        price_now:{
            color:"#E80EAE",
            fontSize:25,
            textAlign:"center",
            paddingTop:10,
            paddingBottom:10,
            fontFamily:"futuraMd"
        },
        price_normal:{
            color:"#A0A0A0",
            fontSize:18,
            fontFamily:"futuraMd"
        },
        desc_txt:{
            textAlign:"justify",
            paddingTop:10,
            fontSize:15,
            fontFamily:"futuraMd"
        },
        label_date:{
            textAlign:"center",
            fontSize:20,
            paddingBottom:10,
            fontFamily:"futuraMd"
        }
    });
    export {ListeStyle}